"""Remotion Renderer — premium composition with FFmpeg fallback.

Consumes timeline JSON generated by EditorAgent and renders through
Remotion CinematicRenderer. If Remotion is unavailable/fails, it
falls back to the existing FFmpeg renderer.
"""
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path
from typing import Optional

from loguru import logger

from config import settings


REMOTION_DIR = Path(__file__).resolve().parent.parent / "remotion-composer"


def is_remotion_available() -> bool:
    """Check if Remotion runtime is available."""
    if not settings.use_remotion:
        return False
    if not REMOTION_DIR.exists():
        return False
    if not (REMOTION_DIR / "package.json").exists():
        return False
    if not (REMOTION_DIR / "node_modules").exists():
        logger.warning("Remotion node_modules missing. Run: cd remotion-composer && npm install")
        return False

    try:
        result = subprocess.run(
            ["node", "--version"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode != 0:
            return False
        logger.debug(f"Node.js: {result.stdout.strip()}")
        return True
    except (FileNotFoundError, subprocess.TimeoutExpired):
        logger.warning("Node.js not found in PATH")
        return False


def render_with_remotion(
    clips: list[Path],
    audio_path: Path,
    subtitles_path: Optional[Path],
    music_path: Optional[Path],
    output_path: Path,
    metadata: dict,
    timeline_path: Optional[Path] = None,
    timeline_payload: Optional[dict] = None,
) -> bool:
    """Render video using Remotion (CinematicRenderer composition)."""
    if not is_remotion_available():
        logger.info("Remotion not available, falling back to FFmpeg")
        return False

    try:
        props: dict
        if timeline_payload:
            props = _normalize_timeline_props(timeline_payload, metadata)
        elif timeline_path and timeline_path.exists():
            payload = json.loads(timeline_path.read_text(encoding="utf-8"))
            props = _normalize_timeline_props(payload, metadata)
        else:
            props = _build_legacy_props(
                clips=clips,
                audio_path=audio_path,
                subtitles_path=subtitles_path,
                music_path=music_path,
                metadata=metadata,
            )

        props_file = output_path.parent / f"remotion_props_{metadata.get('timestamp', 0)}.json"
        props_file.write_text(json.dumps(props, indent=2), encoding="utf-8")

        composition_id = str(metadata.get("composition_id", "CinematicRenderer"))
        logger.info(f"🎥 Remotion: Rendering {len(props.get('scenes', []))} scenes ({composition_id})...")

        cmd = [
            "npx", "remotion", "render",
            "src/index.tsx",
            composition_id,
            str(output_path.resolve()),
            "--props-file", str(props_file.resolve()),
            "--codec", "h264",
            "--concurrency", "2",
        ]

        result = subprocess.run(
            cmd,
            cwd=str(REMOTION_DIR),
            capture_output=True,
            text=True,
            timeout=600,
        )

        props_file.unlink(missing_ok=True)

        if result.returncode == 0 and output_path.exists() and output_path.stat().st_size > 1024:
            size_mb = output_path.stat().st_size / (1024 * 1024)
            logger.info(f"✅ Remotion render complete: {output_path.name} ({size_mb:.1f}MB)")
            return True

        logger.warning(f"Remotion render failed (exit {result.returncode})")
        if result.stderr:
            logger.debug(f"Remotion stderr: {result.stderr[:500]}")
        return False

    except subprocess.TimeoutExpired:
        logger.error("Remotion render timed out (10 min)")
        return False
    except Exception as exc:
        logger.warning(f"Remotion render error: {exc}")
        return False


def render_video_with_fallback(
    clips: list[Path],
    audio_path: Path,
    subs_path: Optional[Path],
    music_path: Optional[Path],
    images: list[Path],
    timestamp: int,
    temp_dir: Path,
    output_dir: Path,
    nicho_slug: str,
    gancho: str,
    titulo: str,
    duracion_audio: float,
    velocidad: str = "rapido",
    num_clips: int = 8,
    duraciones_clips: Optional[list[float]] = None,
    timeline_path: Optional[Path] = None,
    timeline_payload: Optional[dict] = None,
    render_fixes: Optional[dict] = None,
) -> tuple[Optional[Path], Optional[Path], str]:
    """Try Remotion first, then fallback to FFmpeg renderer."""
    from pipeline.renderer import render_video

    if settings.use_remotion:
        if not clips:
            logger.info("Remotion skipped: no video clips detected, using FFmpeg image pipeline")
        else:
            output_dir.mkdir(parents=True, exist_ok=True)
            final_name = f"{_slugify(nicho_slug, 24)}_{_slugify(gancho, 38)}_{timestamp}.mp4"
            remotion_output = output_dir / final_name
            remotion_meta = {
                "timestamp": timestamp,
                "titulo": titulo,
                "nicho": nicho_slug,
                "duration": duracion_audio,
                "transition": "crossfade",
                "composition_id": "CinematicRenderer",
            }

            if render_with_remotion(
                clips=clips,
                audio_path=audio_path,
                subtitles_path=subs_path,
                music_path=music_path,
                output_path=remotion_output,
                metadata=remotion_meta,
                timeline_path=timeline_path,
                timeline_payload=timeline_payload,
            ):
                thumb = _extract_thumbnail(remotion_output, temp_dir, timestamp)
                return remotion_output, thumb, ""

            logger.info("Remotion unavailable/failed, using FFmpeg fallback")

    return render_video(
        clips=clips,
        audio_path=audio_path,
        subs_path=subs_path,
        music_path=music_path,
        images=images,
        timestamp=timestamp,
        temp_dir=temp_dir,
        output_dir=output_dir,
        nicho_slug=nicho_slug,
        gancho=gancho,
        titulo=titulo,
        duracion_audio=duracion_audio,
        velocidad=velocidad,
        num_clips=num_clips,
        duraciones_clips=duraciones_clips,
        render_fixes=render_fixes,
    )


def render_with_fallback(
    clips: list[Path],
    audio_path: Path,
    subtitles_path: Optional[Path],
    music_path: Optional[Path],
    output_path: Path,
    metadata: dict,
) -> bool:
    """Backward-compatible wrapper kept for older callers."""
    return render_with_remotion(clips, audio_path, subtitles_path, music_path, output_path, metadata)


def _extract_thumbnail(video_path: Path, temp_dir: Path, timestamp: int) -> Optional[Path]:
    """Extract a thumbnail frame from rendered video."""
    thumb = temp_dir / f"thumb_{timestamp}.jpg"
    try:
        result = subprocess.run(
            [
                "ffmpeg", "-y", "-ss", "00:00:02",
                "-i", str(video_path.as_posix()),
                "-frames:v", "1",
                str(thumb.as_posix()),
            ],
            capture_output=True,
            text=True,
            timeout=60,
        )
        if result.returncode == 0 and thumb.exists() and thumb.stat().st_size > 100:
            return thumb
    except Exception:
        pass
    return None


def _slugify(text: str, max_len: int = 32) -> str:
    """Convert text to filename-safe slug."""
    slug = (text or "").lower()
    slug = re.sub(r"[^a-z0-9]+", "_", slug)
    slug = slug.strip("_")
    return slug[:max_len] or "video"


def _build_legacy_props(
    clips: list[Path],
    audio_path: Path,
    subtitles_path: Optional[Path],
    music_path: Optional[Path],
    metadata: dict,
) -> dict:
    """Build baseline CinematicRenderer props when no timeline exists."""
    duration = float(metadata.get("duration", 30.0) or 30.0)
    valid_clips = [p for p in clips if p.exists()]
    scenes: list[dict] = []

    if valid_clips:
        scene_dur = max(0.8, duration / max(len(valid_clips), 1))
        cursor = 0.0
        for idx, clip in enumerate(valid_clips):
            scenes.append(
                {
                    "id": f"legacy_scene_{idx + 1}",
                    "kind": "video",
                    "src": _to_file_uri(str(clip.resolve().as_posix())),
                    "startSeconds": round(cursor, 3),
                    "durationSeconds": round(scene_dur, 3),
                    "tone": "steel",
                    "fadeInFrames": 6,
                    "fadeOutFrames": 6,
                    "filter": "contrast(1.06) saturate(0.90) brightness(0.98)",
                }
            )
            cursor += scene_dur
    else:
        scenes.append(
            {
                "id": "legacy_title",
                "kind": "title",
                "text": metadata.get("titulo", "Video Factory"),
                "startSeconds": 0.0,
                "durationSeconds": round(max(3.0, duration), 3),
                "accent": "#86d8ff",
                "intensity": 1.0,
            }
        )

    payload: dict = {
        "scenes": scenes,
        "titleFontSize": 72,
        "titleWidth": 860,
        "signalLineCount": 18,
    }

    if audio_path.exists():
        payload["soundtrack"] = {
            "src": _to_file_uri(str(audio_path.resolve().as_posix())),
            "volume": 1.0,
            "fadeInSeconds": 0.15,
            "fadeOutSeconds": 0.20,
        }

    if music_path and music_path.exists():
        payload["music"] = {
            "src": _to_file_uri(str(music_path.resolve().as_posix())),
            "volume": 0.16,
            "fadeInSeconds": 0.5,
            "fadeOutSeconds": 1.2,
        }

    caption_words = _parse_ass_words(subtitles_path)
    if caption_words:
        payload["captions"] = {
            "words": caption_words,
            "wordsPerPage": 4,
            "fontSize": 52,
            "color": "#F8FAFC",
            "highlightColor": "#FBBF24",
            "backgroundColor": "rgba(0, 0, 0, 0.60)",
        }

    return payload


def _normalize_timeline_props(timeline_payload: dict, metadata: dict) -> dict:
    """Normalize timeline payload into strict CinematicRenderer props."""
    props = dict(timeline_payload or {})
    scenes_raw = props.get("scenes") if isinstance(props.get("scenes"), list) else []

    scenes: list[dict] = []
    for idx, raw in enumerate(scenes_raw):
        if not isinstance(raw, dict):
            continue

        kind = str(raw.get("kind", "video"))
        scene_id = str(raw.get("id") or f"scene_{idx + 1}")
        start_seconds = float(raw.get("startSeconds", 0.0) or 0.0)
        duration_seconds = max(0.8, float(raw.get("durationSeconds", 1.5) or 1.5))

        if kind == "title":
            scenes.append(
                {
                    "id": scene_id,
                    "kind": "title",
                    "text": str(raw.get("text") or metadata.get("titulo") or "Video Factory"),
                    "accent": str(raw.get("accent", "#86d8ff")),
                    "intensity": float(raw.get("intensity", 1.0) or 1.0),
                    "startSeconds": round(start_seconds, 3),
                    "durationSeconds": round(duration_seconds, 3),
                }
            )
            continue

        src = str(raw.get("src", "")).strip()
        if not src:
            continue

        scene: dict = {
            "id": scene_id,
            "kind": "video",
            "src": _to_file_uri(src),
            "startSeconds": round(start_seconds, 3),
            "durationSeconds": round(duration_seconds, 3),
            "tone": str(raw.get("tone", "steel")),
            "fadeInFrames": int(raw.get("fadeInFrames", 6) or 0),
            "fadeOutFrames": int(raw.get("fadeOutFrames", 6) or 0),
            "filter": str(raw.get("filter", "contrast(1.06) saturate(0.90) brightness(0.98)")),
        }

        if "trimBeforeSeconds" in raw:
            scene["trimBeforeSeconds"] = float(raw.get("trimBeforeSeconds") or 0.0)
        if "trimAfterSeconds" in raw:
            scene["trimAfterSeconds"] = float(raw.get("trimAfterSeconds") or 0.0)
        scenes.append(scene)

    if not scenes:
        scenes = [
            {
                "id": "timeline_fallback",
                "kind": "title",
                "text": str(metadata.get("titulo") or "Video Factory"),
                "startSeconds": 0.0,
                "durationSeconds": round(max(3.0, float(metadata.get("duration", 10.0) or 10.0)), 3),
                "accent": "#86d8ff",
                "intensity": 1.0,
            }
        ]

    props["scenes"] = scenes
    props["titleFontSize"] = int(props.get("titleFontSize", 72) or 72)
    props["titleWidth"] = int(props.get("titleWidth", 860) or 860)
    props["signalLineCount"] = int(props.get("signalLineCount", 18) or 18)

    soundtrack = props.get("soundtrack")
    if isinstance(soundtrack, dict) and soundtrack.get("src"):
        props["soundtrack"] = {
            **soundtrack,
            "src": _to_file_uri(str(soundtrack.get("src"))),
        }
    else:
        props.pop("soundtrack", None)

    music = props.get("music")
    if isinstance(music, dict) and music.get("src"):
        props["music"] = {
            **music,
            "src": _to_file_uri(str(music.get("src"))),
        }
    else:
        props.pop("music", None)

    captions = props.get("captions")
    if isinstance(captions, dict) and isinstance(captions.get("words"), list):
        normalized_words = []
        for w in captions.get("words", []):
            if not isinstance(w, dict):
                continue
            word = str(w.get("word", "")).strip()
            if not word:
                continue
            start_ms = int(w.get("startMs", 0) or 0)
            end_ms = int(w.get("endMs", start_ms + 40) or (start_ms + 40))
            if end_ms <= start_ms:
                end_ms = start_ms + 40
            normalized_words.append({"word": word, "startMs": start_ms, "endMs": end_ms})

        if normalized_words:
            props["captions"] = {
                **captions,
                "words": normalized_words,
            }
        else:
            props.pop("captions", None)
    else:
        props.pop("captions", None)

    return props


def _to_file_uri(value: str) -> str:
    """Convert absolute local paths to file:/// URIs for Remotion assets."""
    src = (value or "").strip()
    if not src:
        return src

    lowered = src.lower()
    if lowered.startswith("http://") or lowered.startswith("https://") or lowered.startswith("data:"):
        return src
    if lowered.startswith("file://"):
        return src

    if re.match(r"^[a-zA-Z]:[\\/]", src) or src.startswith("/"):
        try:
            return Path(src).resolve().as_uri()
        except Exception:
            return "file:///" + src.replace("\\", "/")

    return src


def _parse_ass_words(subtitles_path: Optional[Path]) -> list[dict]:
    """Parse ASS subtitles into word-level captions for Remotion overlay."""
    if not subtitles_path or not subtitles_path.exists():
        return []

    words: list[dict] = []
    try:
        lines = subtitles_path.read_text(encoding="utf-8", errors="ignore").splitlines()
        for line in lines:
            if not line.startswith("Dialogue:"):
                continue

            parts = line.split(",", 9)
            if len(parts) < 10:
                continue

            start_s = _ass_time_to_seconds(parts[1])
            end_s = _ass_time_to_seconds(parts[2])
            if end_s <= start_s:
                continue

            text = re.sub(r"\{[^}]*\}", "", parts[9])
            text = text.replace("\\N", " ").replace("\\n", " ")
            text = re.sub(r"\s+", " ", text).strip()
            if not text:
                continue

            tokens = re.findall(r"[A-Za-z0-9ÁÉÍÓÚáéíóúÑñÜü]+|[^\s]", text)
            if not tokens:
                continue

            span = end_s - start_s
            step = span / len(tokens)
            cursor = start_s
            for token in tokens:
                start_ms = int(round(cursor * 1000))
                end_ms = int(round(min(end_s, cursor + step) * 1000))
                if end_ms <= start_ms:
                    end_ms = start_ms + 40
                words.append({"word": token, "startMs": start_ms, "endMs": end_ms})
                cursor += step
    except Exception as exc:
        logger.debug(f"ASS parsing failed for Remotion captions: {exc}")

    return words


def _ass_time_to_seconds(value: str) -> float:
    """Convert ASS timestamp (H:MM:SS.CS) to seconds."""
    try:
        hms, centis = value.strip().split(".")
        hh, mm, ss = hms.split(":")
        return int(hh) * 3600 + int(mm) * 60 + int(ss) + (int(centis) / 100.0)
    except Exception:
        return 0.0


def setup_remotion_project() -> bool:
    """Initialize the Remotion project if not already set up."""
    if REMOTION_DIR.exists() and (REMOTION_DIR / "node_modules").exists():
        logger.debug("Remotion project already initialized")
        return True

    try:
        logger.info("🔧 Setting up Remotion project...")
        REMOTION_DIR.mkdir(parents=True, exist_ok=True)
        result = subprocess.run(
            ["npx", "-y", "create-video@latest", str(REMOTION_DIR), "--template", "blank"],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode == 0:
            logger.info("✅ Remotion project initialized")
            return True

        logger.warning(f"Remotion setup failed: {result.stderr[:300]}")
        return False
    except Exception as exc:
        logger.error(f"Remotion setup error: {exc}")
        return False
