"""Remotion Renderer — premium composition with controlled fallback.

Consumes timeline JSON generated by EditorAgent and renders through
Remotion CinematicRenderer. FFmpeg fallback is controlled by policy
flags in config (ALLOW_FFMPEG_FALLBACK).
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import time
from urllib.parse import unquote
from pathlib import Path
from typing import Optional

from loguru import logger

from config import settings


REMOTION_DIR = Path(__file__).resolve().parent.parent / "remotion-composer"
ALLOWED_REMOTION_COMPOSITIONS = {"CinematicRenderer", "UniversalCommercial"}
DEFAULT_REMOTION_COMPOSITION = "UniversalCommercial"
UNIVERSAL_THEME_DEFAULTS = {
    "clean-professional": {
        "primaryColor": "#2563EB",
        "accentColor": "#F59E0B",
        "fontFamily": "Inter, sans-serif",
    },
    "flat-motion-graphics": {
        "primaryColor": "#7C3AED",
        "accentColor": "#EC4899",
        "fontFamily": "Space Grotesk, sans-serif",
    },
    "minimalist-diagram": {
        "primaryColor": "#1A1A2E",
        "accentColor": "#E94560",
        "fontFamily": "IBM Plex Sans, sans-serif",
    },
    "anime-ghibli": {
        "primaryColor": "#2D5016",
        "accentColor": "#FFB347",
        "fontFamily": "Noto Serif JP, sans-serif",
    },
    "cyberpunk": {
        "primaryColor": "#0F172A",
        "accentColor": "#22D3EE",
        "fontFamily": "Orbitron, sans-serif",
    },
    "minimal": {
        "primaryColor": "#334155",
        "accentColor": "#F97316",
        "fontFamily": "IBM Plex Sans, sans-serif",
    },
    "playful": {
        "primaryColor": "#BE123C",
        "accentColor": "#14B8A6",
        "fontFamily": "Baloo 2, sans-serif",
    },
}


def _resolve_remotion_runner() -> tuple[list[str], str]:
    """Resolve the safest way to execute Remotion CLI.

    Prefer local CLI script via `node` to avoid execute-bit issues on
    `node_modules/.bin/remotion` after cross-OS deployments.
    """
    local_cli_root = REMOTION_DIR / "node_modules" / "@remotion" / "cli"
    local_cli = local_cli_root / "remotion-cli.js"
    local_cli_dist = local_cli_root / "dist" / "index.js"
    if local_cli.exists() and local_cli_dist.exists():
        return ["node", str(local_cli)], "local-cli"

    if local_cli.exists() and not local_cli_dist.exists():
        logger.warning(
            "Remotion local CLI incomplete (missing dist/index.js). "
            "Falling back to npx remotion."
        )

    npx_bin = shutil.which("npx") or shutil.which("npx.cmd")
    if npx_bin:
        return [npx_bin, "remotion"], "npx"

    return [], ""


def get_remotion_unavailability_reason() -> str:
    """Return a short reason when Remotion runtime is not available."""
    if settings.force_ffmpeg_renderer:
        return "FORCE_FFMPEG_RENDERER=true"
    if not settings.use_remotion:
        return "USE_REMOTION=false"
    if not REMOTION_DIR.exists():
        return f"composer dir missing: {REMOTION_DIR}"
    if not (REMOTION_DIR / "package.json").exists():
        return "remotion-composer/package.json missing"
    if not (REMOTION_DIR / "node_modules").exists():
        return "remotion-composer/node_modules missing"

    remotion_runner, _ = _resolve_remotion_runner()
    if not remotion_runner:
        return "Remotion CLI not found (missing local @remotion/cli and npx)"

    try:
        result = subprocess.run(
            ["node", "--version"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode != 0:
            return "node --version failed"

        node_version = (result.stdout or "").strip()
        match = re.match(r"^v?(\d+)", node_version)
        if not match:
            return f"invalid Node.js version output: {node_version or 'unknown'}"
        if int(match.group(1)) < 18:
            return f"Node.js 18+ required (found {node_version})"
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return "Node.js not found in PATH"
    except Exception as exc:
        return f"Node.js probe failed: {exc}"

    return ""


def is_remotion_available() -> bool:
    """Check if Remotion runtime is available."""
    reason = get_remotion_unavailability_reason()
    if reason:
        if "node_modules" in reason:
            logger.warning("Remotion unavailable: node_modules missing. Run: cd remotion-composer && npm install")
        else:
            logger.debug(f"Remotion unavailable: {reason}")
        return False
    return True


def _ensure_public_workspace_link() -> None:
    public_dir = REMOTION_DIR / "public"
    link_path = public_dir / "workspace"
    target = settings.workspace.resolve()
    try:
        public_dir.mkdir(parents=True, exist_ok=True)
        if link_path.exists():
            return
        if settings.is_windows:
            subprocess.run(
                ["cmd", "/c", "mklink", "/J", str(link_path), str(target)],
                capture_output=True,
                text=True,
                timeout=10,
                shell=False,
            )
        else:
            link_path.symlink_to(target, target_is_directory=True)
    except Exception as exc:
        logger.debug(f"Public workspace link skipped: {exc}")


def render_with_remotion(
    clips: list[Path],
    audio_path: Path,
    subtitles_path: Optional[Path],
    music_path: Optional[Path],
    output_path: Path,
    metadata: dict,
    timeline_path: Optional[Path] = None,
    timeline_payload: Optional[dict] = None,
    director_path: Optional[Path] = None,
) -> bool:
    """Render video using the selected Remotion composition."""
    if not is_remotion_available():
        logger.info("Remotion not available, falling back to FFmpeg")
        return False

    requested_concurrency = max(1, int(getattr(settings, "remotion_concurrency", 1) or 1))
    available_cores = max(1, int(os.cpu_count() or 1))
    remotion_concurrency = min(requested_concurrency, available_cores)
    if remotion_concurrency != requested_concurrency:
        logger.warning(
            "Remotion concurrency adjusted to host capacity: "
            f"requested={requested_concurrency}, available={available_cores}, using={remotion_concurrency}"
        )
    remotion_timeout = max(120, int(getattr(settings, "remotion_timeout_seconds", 600) or 600))

    try:
        _ensure_public_workspace_link()
        props: dict
        composition_id = _resolve_composition_id(metadata, timeline_payload)
        if timeline_payload:
            props = _normalize_timeline_props(
                timeline_payload,
                metadata,
                subtitles_path=subtitles_path,
                composition_id=composition_id,
            )
        elif director_path and director_path.exists():
            director_doc = json.loads(director_path.read_text(encoding="utf-8"))
            director_props = director_doc.get("props") if isinstance(director_doc, dict) else {}
            if not isinstance(director_props, dict):
                director_props = {}

            metadata_from_director = dict(metadata)
            if isinstance(director_doc, dict) and director_doc.get("composition_id"):
                metadata_from_director["composition_id"] = str(director_doc.get("composition_id"))

            composition_id = _resolve_composition_id(metadata_from_director, director_props)
            props = _normalize_timeline_props(
                director_props,
                metadata_from_director,
                subtitles_path=subtitles_path,
                composition_id=composition_id,
            )
        elif timeline_path and timeline_path.exists():
            payload = json.loads(timeline_path.read_text(encoding="utf-8"))
            composition_id = _resolve_composition_id(metadata, payload)
            props = _normalize_timeline_props(
                payload,
                metadata,
                subtitles_path=subtitles_path,
                composition_id=composition_id,
            )
        else:
            props = _build_legacy_props(
                clips=clips,
                audio_path=audio_path,
                subtitles_path=subtitles_path,
                music_path=music_path,
                metadata=metadata,
            )
            composition_id = _resolve_composition_id(metadata, None)

        pre_sanitized = _sanitize_non_image_sources_in_props(props, composition_id)
        if pre_sanitized > 0:
            logger.warning(
                "Remotion props sanitized before render: removed/converted {} non-image references",
                pre_sanitized,
            )

        _materialize_workspace_assets(props)

        props_file = output_path.parent / f"remotion_props_{metadata.get('timestamp', 0)}.json"
        props_file.write_text(json.dumps(props, indent=2), encoding="utf-8")

        render_items = _render_item_count(props, composition_id)
        logger.info(f"🎥 Remotion: Rendering {render_items} items ({composition_id})...")

        remotion_runner, runner_kind = _resolve_remotion_runner()
        if not remotion_runner:
            logger.warning("Remotion render aborted: CLI runner not found")
            return False

        output_path_str = str(output_path.resolve().as_posix())

        def _run_remotion_once(payload: dict) -> subprocess.CompletedProcess:
            payload_json = json.dumps(payload, ensure_ascii=False)
            cmd = [
                *remotion_runner,
                "render",
                "src/index.tsx",
                composition_id,
                output_path_str,
                "--props", payload_json,
                "--codec", "h264",
                "--concurrency", str(remotion_concurrency),
            ]
            return subprocess.run(
                cmd,
                cwd=str(REMOTION_DIR),
                capture_output=True,
                text=True,
                timeout=remotion_timeout,
                shell=False,
            )

        result = _run_remotion_once(props)

        props_file.unlink(missing_ok=True)

        if result.stdout:
            logger.debug(f"Remotion stdout: {result.stdout[:2000]}")
        if result.stderr:
            logger.debug(f"Remotion stderr: {result.stderr[:2000]}")

        if result.returncode != 0:
            failed_sources = _extract_failed_image_sources(result.stderr or "")
            if failed_sources:
                repaired = _sanitize_non_image_sources_in_props(
                    props,
                    composition_id,
                    blocked_sources=failed_sources,
                )
                if repaired > 0:
                    logger.warning(
                        "Remotion retry: sanitized {} invalid image source(s) detected at runtime",
                        repaired,
                    )
                    _materialize_workspace_assets(props)
                    props_file.write_text(json.dumps(props, indent=2), encoding="utf-8")
                    result = _run_remotion_once(props)
                    props_file.unlink(missing_ok=True)

                    if result.stdout:
                        logger.debug(f"Remotion retry stdout: {result.stdout[:2000]}")
                    if result.stderr:
                        logger.debug(f"Remotion retry stderr: {result.stderr[:2000]}")

        if result.returncode != 0:
            stderr_snippet = (result.stderr or "").strip().replace("\n", " ")[:500]
            if stderr_snippet:
                logger.warning(
                    f"Remotion render failed (exit {result.returncode}, runner={runner_kind}): "
                    f"{stderr_snippet}"
                )
            else:
                logger.warning(f"Remotion render failed (exit {result.returncode}, runner={runner_kind})")
            return False

        if output_path.exists() and output_path.stat().st_size > 1024:
            suspicious_reason = _remotion_output_quality_issue(output_path)
            if suspicious_reason:
                logger.warning(
                    "Remotion output failed sanity checks "
                    f"({suspicious_reason}). Falling back to FFmpeg."
                )
                output_path.unlink(missing_ok=True)
                return False

            md_error = _sanitize_video_metadata(output_path)
            if md_error:
                logger.warning(f"Remotion metadata cleanup failed (non-fatal): {md_error}")
            size_mb = output_path.stat().st_size / (1024 * 1024)
            logger.info(f"✅ Remotion render complete: {output_path.name} ({size_mb:.1f}MB)")
            return True

        logger.warning(f"Remotion render finished but output file missing or tiny.")
        return False

    except subprocess.TimeoutExpired:
        logger.error(f"Remotion render timed out ({remotion_timeout}s)")
        return False
    except FileNotFoundError:
        logger.error("Remotion executable not found")
        return False
    except Exception as exc:
        logger.warning(f"Remotion render error: {exc}")
        if hasattr(exc, 'stderr') and exc.stderr:
            logger.debug(f"Remotion error detail: {exc.stderr}")
        return False


def render_video_with_fallback(
    clips: list[Path],
    audio_path: Path,
    subs_path: Optional[Path],
    music_path: Optional[Path],
    images: list[Path],
    timestamp: int,
    temp_dir: Path,
    output_dir: Path,
    nicho_slug: str,
    gancho: str,
    titulo: str,
    duracion_audio: float,
    velocidad: str = "rapido",
    num_clips: int = 8,
    duraciones_clips: Optional[list[float]] = None,
    timeline_path: Optional[Path] = None,
    timeline_payload: Optional[dict] = None,
    render_fixes: Optional[dict] = None,
    director_path: Optional[Path] = None,
    style_playbook: str = "",
) -> tuple[Optional[Path], Optional[Path], str, str]:
    """Try Remotion first (when enabled), then fallback to FFmpeg renderer."""
    from pipeline.renderer import render_video

    require_remotion = bool(settings.require_remotion)
    allow_ffmpeg_fallback = bool(settings.allow_ffmpeg_fallback)
    remotion_attempted = False

    # Guard invalid policy combinations early.
    if require_remotion and settings.force_ffmpeg_renderer and not allow_ffmpeg_fallback:
        return None, None, (
            "Invalid renderer policy: REQUIRE_REMOTION=true, "
            "FORCE_FFMPEG_RENDERER=true and ALLOW_FFMPEG_FALLBACK=false"
        ), "none"

    remotion_unavailable_reason = get_remotion_unavailability_reason()

    if settings.force_ffmpeg_renderer and settings.use_remotion:
        logger.info("Remotion renderer forced OFF by config; using FFmpeg renderer")

    if settings.use_remotion and not settings.force_ffmpeg_renderer:
        if not clips and not images:
            logger.info("Remotion skipped: no visual assets detected")
            if require_remotion and not allow_ffmpeg_fallback:
                return None, None, "Remotion required but no visual assets available", "none"
        elif remotion_unavailable_reason:
            if require_remotion and not allow_ffmpeg_fallback:
                return None, None, (
                    "Remotion required but unavailable: "
                    f"{remotion_unavailable_reason}"
                ), "none"
            logger.warning(
                "Remotion unavailable, using FFmpeg emergency fallback: "
                f"{remotion_unavailable_reason}"
            )
        else:
            remotion_attempted = True
            output_dir.mkdir(parents=True, exist_ok=True)
            final_name = f"{_slugify(nicho_slug, 24)}_{_slugify(gancho, 38)}_{timestamp}.mp4"
            remotion_output = output_dir / final_name
            requested_composition = _resolve_composition_id(
                {"composition_id": str(getattr(settings, "remotion_composition_id", DEFAULT_REMOTION_COMPOSITION))},
                timeline_payload,
            )
            remotion_meta = {
                "timestamp": timestamp,
                "titulo": titulo,
                "nicho": nicho_slug,
                "duration": duracion_audio,
                "transition": "crossfade",
                "composition_id": requested_composition,
                "style_playbook": str(style_playbook or "").strip(),
            }

            # Build a timeline dynamically for image-only jobs so Remotion can render
            # cinematic image scenes instead of falling back immediately to FFmpeg.
            if not timeline_payload and not clips and images:
                timeline_payload = _build_image_timeline(
                    images,
                    duracion_audio,
                    composition_id=requested_composition,
                )

            if render_with_remotion(
                clips=clips,
                audio_path=audio_path,
                subtitles_path=subs_path,
                music_path=music_path,
                output_path=remotion_output,
                metadata=remotion_meta,
                timeline_path=timeline_path,
                timeline_payload=timeline_payload,
                director_path=director_path,
            ):
                thumb = _extract_thumbnail(remotion_output, temp_dir, timestamp)
                return remotion_output, thumb, "", "remotion"

            if require_remotion and not allow_ffmpeg_fallback:
                return None, None, (
                    "Remotion required and render failed; "
                    "set ALLOW_FFMPEG_FALLBACK=true only for emergency"
                ), "none"

            logger.info("Remotion failed, using FFmpeg emergency fallback")

    if require_remotion and not allow_ffmpeg_fallback and not remotion_attempted:
        reason = remotion_unavailable_reason or "Remotion disabled by policy"
        return None, None, f"Remotion required but unavailable: {reason}", "none"

    ff_video, ff_thumb, ff_error = render_video(
        clips=clips,
        audio_path=audio_path,
        subs_path=subs_path,
        music_path=music_path,
        images=images,
        timestamp=timestamp,
        temp_dir=temp_dir,
        output_dir=output_dir,
        nicho_slug=nicho_slug,
        gancho=gancho,
        titulo=titulo,
        duracion_audio=duracion_audio,
        velocidad=velocidad,
        num_clips=num_clips,
        duraciones_clips=duraciones_clips,
        render_fixes=render_fixes,
    )
    return ff_video, ff_thumb, ff_error, "ffmpeg"


def _build_image_timeline(
    images: list[Path],
    duration: float,
    composition_id: str = DEFAULT_REMOTION_COMPOSITION,
) -> dict:
    """Build a Remotion timeline for images using Parallax/Ken Burns."""
    valid_images = [img for img in images if img.exists()]
    if not valid_images:
        return {}

    scene_dur = max(0.8, duration / len(valid_images))
    scenes = []
    cursor = 0.0
    animations = ["parallax", "kenBurns", "panCross", "zoomPulse"]
    from itertools import cycle
    anim_cycle = cycle(animations)
    
    for idx, img in enumerate(valid_images):
        scenes.append({
            "id": f"image_scene_{idx + 1}",
            "kind": "image",
            "src": str(img.resolve()),
            "startSeconds": round(cursor, 3),
            "durationSeconds": round(scene_dur, 3),
            "animation": next(anim_cycle),
            "animationIntensity": 1.2,
            "tone": "neutral",
            "overlayParticles": True,
            "fadeInFrames": 15 if idx > 0 else 0,
            "fadeOutFrames": 15 if idx < len(valid_images) - 1 else 0,
            "filter": "contrast(1.05) saturate(1.1) brightness(0.95)",
        })
        cursor += scene_dur

    return {
        "composition_id": composition_id,
        "meta": {"composition_id": composition_id},
        "scenes": scenes,
    }


def render_with_fallback(
    clips: list[Path],
    audio_path: Path,
    subtitles_path: Optional[Path],
    music_path: Optional[Path],
    output_path: Path,
    metadata: dict,
) -> bool:
    """Backward-compatible wrapper kept for older callers."""
    return render_with_remotion(clips, audio_path, subtitles_path, music_path, output_path, metadata)


def _extract_thumbnail(video_path: Path, temp_dir: Path, timestamp: int) -> Optional[Path]:
    """Extract a thumbnail frame from rendered video."""
    thumb = temp_dir / f"thumb_{timestamp}.jpg"
    try:
        result = subprocess.run(
            [
                "ffmpeg", "-y", "-ss", "00:00:02",
                "-i", str(video_path.as_posix()),
                "-frames:v", "1",
                str(thumb.as_posix()),
            ],
            capture_output=True,
            text=True,
            timeout=60,
        )
        if result.returncode == 0 and thumb.exists() and thumb.stat().st_size > 100:
            return thumb
    except Exception:
        pass
    return None


def _slugify(text: str, max_len: int = 32) -> str:
    """Convert text to filename-safe slug."""
    slug = (text or "").lower()
    slug = re.sub(r"[^a-z0-9]+", "_", slug)
    slug = slug.strip("_")
    return slug[:max_len] or "video"


def _privacy_ffmpeg_args() -> list[str]:
    """Common FFmpeg args to strip container metadata from outputs."""
    return [
        "-map_metadata", "-1",
        "-metadata", "title=",
        "-metadata", "comment=",
        "-metadata", "description=",
        "-metadata", "artist=",
        "-metadata", "copyright=",
        "-metadata", "encoder=",
    ]


def _sanitize_video_metadata(video_path: Path) -> str:
    """Final metadata-strip pass with stream copy to preserve quality."""
    clean_path = video_path.with_name(f"{video_path.stem}_cleanmeta{video_path.suffix}")
    try:
        result = subprocess.run(
            [
                "ffmpeg", "-y", "-threads", "2",
                "-i", str(video_path.as_posix()),
                "-map", "0:v:0", "-map", "0:a?",
                "-c", "copy",
                "-movflags", "+faststart",
                *_privacy_ffmpeg_args(),
                str(clean_path.as_posix()),
            ],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode != 0:
            return (result.stderr or "ffmpeg metadata strip failed")[-240:]

        if not clean_path.exists() or clean_path.stat().st_size <= 1024:
            clean_path.unlink(missing_ok=True)
            return "metadata strip produced invalid file"

        video_path.unlink(missing_ok=True)
        clean_path.rename(video_path)
        return ""
    except Exception as exc:
        clean_path.unlink(missing_ok=True)
        return str(exc)


def _build_legacy_props(
    clips: list[Path],
    audio_path: Path,
    subtitles_path: Optional[Path],
    music_path: Optional[Path],
    metadata: dict,
) -> dict:
    """Build baseline CinematicRenderer props when no timeline exists."""
    duration = float(metadata.get("duration", 30.0) or 30.0)
    valid_clips = [p for p in clips if p.exists() and p.stat().st_size > 1000]
    scenes: list[dict] = []

    if valid_clips:
        scene_dur = max(0.8, duration / max(len(valid_clips), 1))
        cursor = 0.0
        for idx, clip in enumerate(valid_clips):
            scenes.append(
                {
                    "id": f"legacy_scene_{idx + 1}",
                    "kind": "video",
                    "src": _to_file_uri(str(clip.resolve().as_posix())),
                    "startSeconds": round(cursor, 3),
                    "durationSeconds": round(scene_dur, 3),
                    "tone": "steel",
                    "fadeInFrames": 6,
                    "fadeOutFrames": 6,
                    "filter": "contrast(1.06) saturate(0.90) brightness(0.98)",
                }
            )
            cursor += scene_dur
    else:
        scenes.append(
            {
                "id": "legacy_title",
                "kind": "title",
                "text": metadata.get("titulo", "Video Factory"),
                "startSeconds": 0.0,
                "durationSeconds": round(max(3.0, duration), 3),
                "accent": "#86d8ff",
                "intensity": 1.0,
            }
        )

    payload: dict = {
        "scenes": scenes,
        "titleFontSize": 72,
        "titleWidth": 860,
        "signalLineCount": 18,
    }

    if audio_path.exists():
        payload["soundtrack"] = {
            "src": _to_file_uri(str(audio_path.resolve().as_posix())),
            "volume": 1.0,
            "fadeInSeconds": 0.15,
            "fadeOutSeconds": 0.20,
        }

    if music_path and music_path.exists():
        payload["music"] = {
            "src": _to_file_uri(str(music_path.resolve().as_posix())),
            "volume": 0.16,
            "fadeInSeconds": 0.5,
            "fadeOutSeconds": 1.2,
        }

    caption_words = _parse_ass_words(subtitles_path)
    if caption_words:
        payload["captions"] = {
            "words": caption_words,
            "wordsPerPage": 4,
            "fontSize": 52,
            "color": "#F8FAFC",
            "highlightColor": "#FBBF24",
            "backgroundColor": "rgba(0, 0, 0, 0.60)",
        }

    return payload


def _normalize_timeline_props(
    timeline_payload: dict,
    metadata: dict,
    subtitles_path: Optional[Path] = None,
    composition_id: str = DEFAULT_REMOTION_COMPOSITION,
) -> dict:
    """Normalize timeline payload into strict composition-specific props."""
    props = dict(timeline_payload or {})
    if composition_id == "UniversalCommercial":
        return _normalize_universal_commercial_props(props, metadata)

    scenes_raw = props.get("scenes") if isinstance(props.get("scenes"), list) else []
    scenes: list[dict] = []
    for idx, raw in enumerate(scenes_raw):
        if not isinstance(raw, dict):
            continue

        kind = str(raw.get("kind", "video")).strip().lower()
        if kind not in {"video", "image", "title"}:
            kind = "video"
        scene_id = str(raw.get("id") or f"scene_{idx + 1}")
        start_seconds = float(raw.get("startSeconds", 0.0) or 0.0)
        duration_seconds = max(0.8, float(raw.get("durationSeconds", 1.5) or 1.5))

        if kind == "title":
            scenes.append(
                {
                    "id": scene_id,
                    "kind": "title",
                    "text": str(raw.get("text") or metadata.get("titulo") or "Video Factory"),
                    "accent": str(raw.get("accent", "#86d8ff")),
                    "intensity": float(raw.get("intensity", 1.0) or 1.0),
                    "startSeconds": round(start_seconds, 3),
                    "durationSeconds": round(duration_seconds, 3),
                }
            )
            continue

        src = str(raw.get("src", "")).strip()
        if not src:
            continue

        raw_path = src.replace("file://", "").replace("file:///", "").split("?")[0]
        try:
            p = Path(raw_path)
            if p.exists() and p.stat().st_size < 100:
                logger.warning(f"Discarding empty media file: {src}")
                continue
        except Exception:
            pass

        scene: dict = {
            "id": scene_id,
            "kind": kind,
            "src": _to_file_uri(src),
            "startSeconds": round(start_seconds, 3),
            "durationSeconds": round(duration_seconds, 3),
            "tone": str(raw.get("tone", "steel")),
            "fadeInFrames": int(raw.get("fadeInFrames", 6) or 0),
            "fadeOutFrames": int(raw.get("fadeOutFrames", 6) or 0),
            "filter": str(raw.get("filter", "contrast(1.06) saturate(0.90) brightness(0.98)")),
        }

        if kind == "image" and _is_non_image_asset_path(str(scene.get("src") or "")):
            # Defensive normalization: malformed timelines may tag video files as image scenes.
            scene["kind"] = "video"

        if scene.get("kind") == "image":
            if "animation" in raw:
                scene["animation"] = str(raw["animation"])
            if "animationIntensity" in raw:
                scene["animationIntensity"] = float(raw["animationIntensity"])
            if "animationDirection" in raw:
                scene["animationDirection"] = str(raw["animationDirection"])
            if "overlayParticles" in raw:
                scene["overlayParticles"] = bool(raw["overlayParticles"])

        if "trimBeforeSeconds" in raw:
            scene["trimBeforeSeconds"] = float(raw.get("trimBeforeSeconds") or 0.0)
        if "trimAfterSeconds" in raw:
            scene["trimAfterSeconds"] = float(raw.get("trimAfterSeconds") or 0.0)
        scenes.append(scene)

    if not scenes:
        scenes = [
            {
                "id": "timeline_fallback",
                "kind": "title",
                "text": str(metadata.get("titulo") or "Video Factory"),
                "startSeconds": 0.0,
                "durationSeconds": round(max(3.0, float(metadata.get("duration", 10.0) or 10.0)), 3),
                "accent": "#86d8ff",
                "intensity": 1.0,
            }
        ]

    props["scenes"] = scenes
    props["titleFontSize"] = int(props.get("titleFontSize", 72) or 72)
    props["titleWidth"] = int(props.get("titleWidth", 860) or 860)
    props["signalLineCount"] = int(props.get("signalLineCount", 18) or 18)

    soundtrack = props.get("soundtrack")
    if isinstance(soundtrack, dict) and soundtrack.get("src"):
        props["soundtrack"] = {
            **soundtrack,
            "src": _to_file_uri(str(soundtrack.get("src"))),
        }
    else:
        props.pop("soundtrack", None)

    music = props.get("music")
    if isinstance(music, dict) and music.get("src"):
        props["music"] = {
            **music,
            "src": _to_file_uri(str(music.get("src"))),
        }
    else:
        props.pop("music", None)

    captions = props.get("captions") if isinstance(props.get("captions"), dict) else {}
    normalized_words: list[dict] = []

    if isinstance(captions.get("words"), list):
        for w in captions.get("words", []):
            if not isinstance(w, dict):
                continue
            word = str(w.get("word", "")).strip()
            if not word:
                continue
            start_ms = int(w.get("startMs", 0) or 0)
            end_ms = int(w.get("endMs", start_ms + 40) or (start_ms + 40))
            if end_ms <= start_ms:
                end_ms = start_ms + 40
            normalized_words.append({"word": word, "startMs": start_ms, "endMs": end_ms})

    if not normalized_words and subtitles_path and subtitles_path.exists():
        normalized_words = _parse_ass_words(subtitles_path)
        if normalized_words:
            logger.info("Remotion captions fallback applied from ASS subtitles")

    if normalized_words:
        props["captions"] = {
            **captions,
            "words": normalized_words,
            "wordsPerPage": int(captions.get("wordsPerPage", 4) or 4),
            "fontSize": int(captions.get("fontSize", 52) or 52),
            "color": str(captions.get("color", "#F8FAFC")),
            "highlightColor": str(captions.get("highlightColor", "#FBBF24")),
            "backgroundColor": str(captions.get("backgroundColor", "rgba(0, 0, 0, 0.60)")),
        }
    else:
        props.pop("captions", None)

    return props


def build_director_artifacts(
    timeline_payload: dict,
    metadata: dict,
    artifacts_dir: Path,
    *,
    subtitles_path: Optional[Path] = None,
) -> tuple[Path, Path, dict, dict]:
    """Build, validate, and persist director artifacts for auditability.

    Returns:
        (director_json_path, director_meta_path, director_payload, director_meta)
    """
    payload = dict(timeline_payload or {})
    composition_id = _resolve_composition_id(metadata, payload)
    normalized_props = _normalize_timeline_props(
        payload,
        metadata,
        subtitles_path=subtitles_path,
        composition_id=composition_id,
    )

    try:
        timestamp = int(metadata.get("timestamp") or int(time.time() * 1000))
    except (TypeError, ValueError, AttributeError):
        timestamp = int(time.time() * 1000)

    director_payload = {
        "version": "1.0",
        "composition_id": composition_id,
        "timestamp": timestamp,
        "job_id": str(metadata.get("job_id") or ""),
        "props": normalized_props,
    }

    props_hash = hashlib.sha1(
        json.dumps(normalized_props, ensure_ascii=False, sort_keys=True).encode("utf-8")
    ).hexdigest()
    director_meta = {
        "version": "1.0",
        "composition_id": composition_id,
        "timestamp": timestamp,
        "job_id": str(metadata.get("job_id") or ""),
        "props_hash": props_hash,
        "render_item_count": int(_render_item_count(normalized_props, composition_id)),
        "asset_reference_count": int(_count_asset_references(normalized_props, composition_id)),
        "has_captions": bool(normalized_props.get("captions")),
        "has_soundtrack": bool(isinstance(normalized_props.get("soundtrack"), dict)),
        "has_music": bool(isinstance(normalized_props.get("music"), dict)),
    }

    from schemas.artifacts import validate_artifact

    validate_artifact("director", director_payload)
    validate_artifact("director_meta", director_meta)

    artifacts_dir.mkdir(parents=True, exist_ok=True)
    director_path = artifacts_dir / f"director_{timestamp}.json"
    director_meta_path = artifacts_dir / f"director_meta_{timestamp}.json"

    director_path.write_text(
        json.dumps(director_payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    director_meta_path.write_text(
        json.dumps(director_meta, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    return director_path, director_meta_path, director_payload, director_meta


def build_edit_decisions_artifact(
    timeline_payload: dict,
    metadata: dict,
    artifacts_dir: Path,
    *,
    subtitles_path: Optional[Path] = None,
    narration_audio_path: Optional[Path] = None,
    music_path: Optional[Path] = None,
    incremental_eml_seed: Optional[dict] = None,
) -> tuple[Path, dict]:
    """Build, validate, and persist an OpenMontage-compatible edit_decisions artifact."""
    payload = dict(timeline_payload or {})
    composition_id = _resolve_composition_id(metadata, payload)
    normalized_props = _normalize_timeline_props(
        payload,
        metadata,
        subtitles_path=subtitles_path,
        composition_id=composition_id,
    )

    try:
        timestamp = int(metadata.get("timestamp") or int(time.time() * 1000))
    except (TypeError, ValueError, AttributeError):
        timestamp = int(time.time() * 1000)

    cuts = _build_edit_decision_cuts(normalized_props, composition_id)
    mapper_name = "timeline"
    mapper_fallback = False

    if not cuts:
        seed_cuts = _extract_incremental_seed_cuts(incremental_eml_seed)
        if seed_cuts:
            cuts = seed_cuts
            mapper_name = "editor_incremental"
            mapper_fallback = True

    seed_cut_count = 0
    if isinstance(incremental_eml_seed, dict) and isinstance(incremental_eml_seed.get("cuts"), list):
        seed_cut_count = len(incremental_eml_seed.get("cuts") or [])

    edit_decisions: dict = {
        "version": "1.0",
        "cuts": cuts,
        "renderer_family": "animation-first",
        "metadata": {
            "composition_id": composition_id,
            "timestamp": timestamp,
            "job_id": str(metadata.get("job_id") or ""),
            "generated_by": "renderer_remotion.build_edit_decisions_artifact",
            "render_item_count": int(_render_item_count(normalized_props, composition_id)),
            "asset_reference_count": int(_count_asset_references(normalized_props, composition_id)),
            "cut_mapper": mapper_name,
            "cut_mapper_fallback": mapper_fallback,
            "incremental_seed_cut_count": int(seed_cut_count),
        },
    }

    subtitles_payload = _build_edit_decisions_subtitles(
        subtitles_path=subtitles_path,
        normalized_props=normalized_props,
    )
    if subtitles_payload:
        edit_decisions["subtitles"] = subtitles_payload

    audio_payload, legacy_music = _build_edit_decisions_audio(
        normalized_props=normalized_props,
        composition_id=composition_id,
        narration_audio_path=narration_audio_path,
        music_path=music_path,
    )
    if audio_payload:
        edit_decisions["audio"] = audio_payload
    if legacy_music:
        edit_decisions["music"] = legacy_music

    from schemas.artifacts import validate_artifact

    validate_artifact("edit_decisions", edit_decisions)

    artifacts_dir.mkdir(parents=True, exist_ok=True)
    edit_decisions_path = artifacts_dir / f"edit_decisions_{timestamp}.json"
    edit_decisions_path.write_text(
        json.dumps(edit_decisions, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return edit_decisions_path, edit_decisions


def _build_edit_decision_cuts(normalized_props: dict, composition_id: str) -> list[dict]:
    """Map composition-specific props to edit_decisions.cuts format."""
    if composition_id == "UniversalCommercial":
        script = normalized_props.get("script") if isinstance(normalized_props.get("script"), dict) else {}
        features = script.get("features") if isinstance(script.get("features"), list) else []
        cuts: list[dict] = []
        for idx, feature in enumerate(features):
            if not isinstance(feature, dict):
                continue
            image_path = str(feature.get("imagePath") or "").strip()
            if not image_path:
                continue

            duration = 6.0
            title = str(feature.get("title") or f"Feature {idx + 1}")
            cuts.append(
                {
                    "id": f"feature_{idx + 1}",
                    "source": _to_file_uri(image_path),
                    "in_seconds": 0.0,
                    "out_seconds": duration,
                    "layer": "primary",
                    "transform": {
                        "scale": 1.0,
                        "position": "center",
                        "animation": "ken-burns-slow-zoom",
                    },
                    "transition_in": "cut",
                    "transition_out": "cut",
                    "transition_duration": 0.15,
                    "reason": f"Feature visual: {title[:120]}",
                }
            )
        return cuts

    scenes = normalized_props.get("scenes") if isinstance(normalized_props.get("scenes"), list) else []
    cuts = []
    for idx, scene in enumerate(scenes):
        if not isinstance(scene, dict):
            continue

        src = str(scene.get("src") or "").strip()
        if not src:
            continue

        try:
            duration = max(0.8, float(scene.get("durationSeconds", 0.0) or 0.0))
        except (TypeError, ValueError):
            duration = 0.8

        try:
            speed = max(0.1, float(scene.get("speedFactor", 1.0) or 1.0))
        except (TypeError, ValueError):
            speed = 1.0

        zoom_animation = _zoom_to_transform_animation(str(scene.get("zoomType") or ""))
        transform: dict = {
            "scale": 1.0,
            "position": "center",
        }
        if zoom_animation:
            transform["animation"] = zoom_animation

        try:
            fade_out_frames = int(scene.get("fadeOutFrames", 0) or 0)
        except (TypeError, ValueError):
            fade_out_frames = 0

        cut = {
            "id": str(scene.get("id") or f"cut_{idx + 1}"),
            "source": _to_file_uri(src),
            "in_seconds": 0.0,
            "out_seconds": round(duration, 3),
            "speed": speed,
            "layer": "primary",
            "transform": transform,
            "transition_in": "cut",
            "transition_out": _normalize_cut_transition(str(scene.get("transitionOut") or "cut")),
            "transition_duration": round(max(0.0, fade_out_frames / 30.0), 3),
        }

        reason = str(scene.get("sceneText") or "").strip()
        if reason:
            cut["reason"] = reason[:180]

        cuts.append(cut)

    return cuts


def _extract_incremental_seed_cuts(incremental_eml_seed: Optional[dict]) -> list[dict]:
    """Extract schema-safe cuts from editor incremental EML seed payload."""
    if not isinstance(incremental_eml_seed, dict):
        return []

    raw_cuts = incremental_eml_seed.get("cuts")
    if not isinstance(raw_cuts, list):
        return []

    cuts: list[dict] = []
    for idx, item in enumerate(raw_cuts):
        if not isinstance(item, dict):
            continue

        source = str(item.get("source") or "").strip()
        if not source:
            continue

        try:
            in_seconds = max(0.0, float(item.get("in_seconds", 0.0) or 0.0))
        except (TypeError, ValueError):
            in_seconds = 0.0

        try:
            out_seconds = max(0.0, float(item.get("out_seconds", 0.0) or 0.0))
        except (TypeError, ValueError):
            out_seconds = 0.0

        if out_seconds <= in_seconds:
            out_seconds = round(in_seconds + 0.8, 3)

        cut: dict = {
            "id": str(item.get("id") or f"seed_cut_{idx + 1}"),
            "source": _to_file_uri(source),
            "in_seconds": round(in_seconds, 3),
            "out_seconds": round(out_seconds, 3),
        }

        try:
            speed = max(0.1, float(item.get("speed", 1.0) or 1.0))
            cut["speed"] = speed
        except (TypeError, ValueError):
            pass

        layer = str(item.get("layer") or "").strip().lower()
        if layer in {"primary", "overlay", "background"}:
            cut["layer"] = layer

        transform = item.get("transform") if isinstance(item.get("transform"), dict) else None
        if transform:
            clean_transform: dict = {}
            if "scale" in transform:
                try:
                    clean_transform["scale"] = max(0.0, float(transform.get("scale") or 0.0))
                except (TypeError, ValueError):
                    pass
            if "position" in transform:
                clean_transform["position"] = str(transform.get("position") or "center")
            if "animation" in transform:
                clean_transform["animation"] = str(transform.get("animation") or "")
            if clean_transform:
                cut["transform"] = clean_transform

        transition_in = str(item.get("transition_in") or "").strip()
        if transition_in:
            cut["transition_in"] = transition_in
        transition_out = str(item.get("transition_out") or "").strip()
        if transition_out:
            cut["transition_out"] = transition_out

        if "transition_duration" in item:
            try:
                cut["transition_duration"] = max(0.0, float(item.get("transition_duration") or 0.0))
            except (TypeError, ValueError):
                pass

        reason = str(item.get("reason") or "").strip()
        if reason:
            cut["reason"] = reason[:180]

        cuts.append(cut)

    return cuts


def _normalize_cut_transition(value: str) -> str:
    clean = (value or "").strip().lower().replace("-", "_").replace(" ", "_")
    mapping = {
        "cut": "cut",
        "hard_cut": "cut",
        "none": "cut",
        "fade": "fade",
        "crossfade": "dissolve",
        "dissolve": "dissolve",
        "wipe": "wipe",
        "whip": "wipe",
        "slide": "wipe",
    }
    return mapping.get(clean, "cut")


def _zoom_to_transform_animation(value: str) -> str:
    clean = (value or "").strip().lower().replace("-", "_").replace(" ", "_")
    mapping = {
        "ken_burns": "ken-burns-slow-zoom",
        "zoom_in": "zoom-in",
        "zoom_out": "zoom-out",
    }
    return mapping.get(clean, "")


def _build_edit_decisions_subtitles(
    *,
    subtitles_path: Optional[Path],
    normalized_props: dict,
) -> Optional[dict]:
    subtitles: dict = {
        "enabled": False,
        "style": "word-by-word",
        "position": "bottom-center",
    }

    if subtitles_path and subtitles_path.exists():
        subtitles.update(
            {
                "enabled": True,
                "source": _to_file_uri(str(subtitles_path.resolve().as_posix())),
                "font": "IBM Plex Sans",
                "font_size": 52,
                "color": "#F8FAFC",
                "outline_color": "#000000",
                "background": "#00000099",
                "max_words_per_line": 4,
            }
        )
        return subtitles

    captions = normalized_props.get("captions") if isinstance(normalized_props.get("captions"), dict) else {}
    words = captions.get("words") if isinstance(captions.get("words"), list) else []
    if not words:
        return None

    subtitles.update(
        {
            "enabled": True,
            "font_size": int(captions.get("fontSize", 52) or 52),
            "color": str(captions.get("color", "#F8FAFC")),
            "outline_color": "#000000",
            "background": str(captions.get("backgroundColor", "#00000099")),
            "max_words_per_line": int(captions.get("wordsPerPage", 4) or 4),
        }
    )
    return subtitles


def _build_edit_decisions_audio(
    *,
    normalized_props: dict,
    composition_id: str,
    narration_audio_path: Optional[Path],
    music_path: Optional[Path],
) -> tuple[Optional[dict], Optional[dict]]:
    audio_payload: dict = {}
    legacy_music: Optional[dict] = None

    narration_src = ""
    if narration_audio_path and narration_audio_path.exists():
        narration_src = _to_file_uri(str(narration_audio_path.resolve().as_posix()))
    else:
        soundtrack = normalized_props.get("soundtrack") if isinstance(normalized_props.get("soundtrack"), dict) else {}
        if soundtrack.get("src"):
            narration_src = _to_file_uri(str(soundtrack.get("src")))

    if narration_src:
        audio_payload["narration"] = {
            "segments": [
                {
                    "asset_id": narration_src,
                    "start_seconds": 0.0,
                }
            ]
        }

    music_src = ""
    music_volume = 0.16
    fade_in = 0.5
    fade_out = 1.2

    if composition_id == "UniversalCommercial":
        audio_cfg = normalized_props.get("audio") if isinstance(normalized_props.get("audio"), dict) else {}
        music_src = str(audio_cfg.get("bgmPath") or "").strip()
        try:
            music_volume = float(audio_cfg.get("volume", 0.4) or 0.4)
        except (TypeError, ValueError):
            music_volume = 0.4
    else:
        music = normalized_props.get("music") if isinstance(normalized_props.get("music"), dict) else {}
        music_src = str(music.get("src") or "").strip()
        try:
            music_volume = float(music.get("volume", 0.16) or 0.16)
        except (TypeError, ValueError):
            music_volume = 0.16
        try:
            fade_in = float(music.get("fadeInSeconds", 0.5) or 0.5)
        except (TypeError, ValueError):
            fade_in = 0.5
        try:
            fade_out = float(music.get("fadeOutSeconds", 1.2) or 1.2)
        except (TypeError, ValueError):
            fade_out = 1.2

    if not music_src and music_path and music_path.exists():
        music_src = _to_file_uri(str(music_path.resolve().as_posix()))

    if music_src:
        music_src = _to_file_uri(music_src)
        music_volume = max(0.0, min(1.0, music_volume))
        fade_in = max(0.0, fade_in)
        fade_out = max(0.0, fade_out)

        music_payload = {
            "asset_id": music_src,
            "volume": music_volume,
            "fade_in_seconds": fade_in,
            "fade_out_seconds": fade_out,
            "ducking": True,
        }
        audio_payload["music"] = music_payload
        legacy_music = dict(music_payload)

    if not audio_payload:
        return None, None
    return audio_payload, legacy_music


def _resolve_composition_id(metadata: dict, timeline_payload: Optional[dict]) -> str:
    """Resolve composition ID from timeline payload first, then metadata."""
    candidate = ""
    if isinstance(timeline_payload, dict):
        candidate = str(
            timeline_payload.get("composition_id")
            or timeline_payload.get("compositionId")
            or ""
        ).strip()

        if not candidate:
            meta = timeline_payload.get("meta")
            if isinstance(meta, dict):
                candidate = str(meta.get("composition_id") or meta.get("compositionId") or "").strip()

    if not candidate:
        candidate = str(metadata.get("composition_id") or "").strip()

    resolved = candidate or DEFAULT_REMOTION_COMPOSITION
    if resolved not in ALLOWED_REMOTION_COMPOSITIONS:
        logger.warning(
            "Unknown remotion composition in payload/metadata ({}). Falling back to {}.",
            resolved,
            DEFAULT_REMOTION_COMPOSITION,
        )
        return DEFAULT_REMOTION_COMPOSITION
    return resolved


def _render_item_count(props: dict, composition_id: str) -> int:
    """Estimate render item count for log visibility across compositions."""
    if composition_id == "UniversalCommercial":
        script = props.get("script") if isinstance(props.get("script"), dict) else {}
        features = script.get("features") if isinstance(script.get("features"), list) else []
        return len(features) + 3

    scenes = props.get("scenes") if isinstance(props.get("scenes"), list) else []
    return len(scenes)


def _count_asset_references(props: dict, composition_id: str) -> int:
    """Count explicit media references included in normalized render props."""
    refs = 0

    if composition_id == "UniversalCommercial":
        script = props.get("script") if isinstance(props.get("script"), dict) else {}
        features = script.get("features") if isinstance(script.get("features"), list) else []
        for feature in features:
            if isinstance(feature, dict) and str(feature.get("imagePath") or "").strip():
                refs += 1

        audio = props.get("audio") if isinstance(props.get("audio"), dict) else {}
        if str(audio.get("bgmPath") or "").strip():
            refs += 1
        return refs

    scenes = props.get("scenes") if isinstance(props.get("scenes"), list) else []
    for scene in scenes:
        if isinstance(scene, dict) and str(scene.get("src") or "").strip():
            refs += 1

    soundtrack = props.get("soundtrack")
    if isinstance(soundtrack, dict) and str(soundtrack.get("src") or "").strip():
        refs += 1

    music = props.get("music")
    if isinstance(music, dict) and str(music.get("src") or "").strip():
        refs += 1

    return refs


def _normalize_static_asset_path(value: str) -> str:
    """Return a staticFile-compatible path (workspace relative) when possible."""
    normalized = _to_file_uri(str(value or "").strip())
    if not normalized:
        return ""

    lowered = normalized.lower()
    if lowered.startswith("workspace/"):
        return normalized

    if lowered.startswith("http://") or lowered.startswith("https://") or lowered.startswith("data:"):
        return ""
    if lowered.startswith("file://"):
        return ""

    if normalized.startswith("/") or normalized.startswith("\\") or ":" in normalized:
        return ""

    return normalized.replace("\\", "/")


_NON_IMAGE_ASSET_EXTENSIONS = {
    ".mp4", ".mov", ".m4v", ".webm", ".mkv", ".avi", ".wmv", ".flv", ".mpeg", ".mpg", ".ts", ".m2ts", ".3gp",
    ".mp3", ".wav", ".aac", ".m4a", ".ogg", ".flac", ".opus", ".aif", ".aiff", ".wma",
}


def _is_non_image_asset_path(value: str) -> bool:
    """Return True when a path clearly points to video/audio media."""
    src = str(value or "").strip()
    if not src:
        return False

    lowered = src.lower()
    if lowered.startswith("data:image/"):
        return False

    candidate = src.split("?", 1)[0].split("#", 1)[0].strip()
    if candidate.lower().startswith("file://"):
        candidate = unquote(candidate[7:])

    suffix = Path(candidate).suffix.lower()
    if not suffix:
        return False

    return suffix in _NON_IMAGE_ASSET_EXTENSIONS


def _normalize_universal_commercial_props(timeline_payload: dict, metadata: dict) -> dict:
    """Normalize flexible payloads into UniversalCommercial props contract."""
    raw_style = timeline_payload.get("style") if isinstance(timeline_payload.get("style"), dict) else {}
    raw_project = timeline_payload.get("projectInfo") if isinstance(timeline_payload.get("projectInfo"), dict) else {}
    raw_script = timeline_payload.get("script") if isinstance(timeline_payload.get("script"), dict) else {}
    raw_meta = timeline_payload.get("meta") if isinstance(timeline_payload.get("meta"), dict) else {}
    raw_theme_config = timeline_payload.get("themeConfig")
    if not isinstance(raw_theme_config, dict):
        raw_theme_config = raw_style.get("themeConfig") if isinstance(raw_style.get("themeConfig"), dict) else {}
    if not isinstance(raw_theme_config, dict):
        raw_theme_config = raw_meta.get("themeConfig") if isinstance(raw_meta.get("themeConfig"), dict) else {}

    theme = str(
        raw_style.get("theme")
        or timeline_payload.get("theme")
        or raw_meta.get("theme")
        or raw_meta.get("playbook")
        or timeline_payload.get("playbook")
        or metadata.get("style_playbook")
        or "minimal"
    ).strip().lower()
    if theme not in UNIVERSAL_THEME_DEFAULTS:
        theme = "minimal"

    theme_defaults = UNIVERSAL_THEME_DEFAULTS[theme]

    project_name = str(
        raw_project.get("name")
        or metadata.get("titulo")
        or metadata.get("nicho")
        or "Video Factory"
    ).strip()

    playbook = str(
        timeline_payload.get("playbook")
        or raw_meta.get("playbook")
        or metadata.get("style_playbook")
        or ""
    ).strip().lower()

    style_profile = raw_meta.get("style_profile") if isinstance(raw_meta.get("style_profile"), dict) else {}
    layout_variant = str(
        raw_style.get("layoutVariant")
        or timeline_payload.get("layoutVariant")
        or raw_meta.get("layoutVariant")
        or ("stacked" if theme in {"minimal", "minimalist-diagram"} else "split")
    ).strip().lower()
    if layout_variant not in {"split", "stacked", "spotlight"}:
        layout_variant = "split"

    kinetic_level = str(
        raw_style.get("kineticLevel")
        or timeline_payload.get("kineticLevel")
        or raw_meta.get("kineticLevel")
        or ""
    ).strip().lower()
    if not kinetic_level:
        cut_speed = str(style_profile.get("cut_speed") or "").strip().lower()
        if cut_speed == "ultra_rapido":
            kinetic_level = "intense"
        elif cut_speed in {"rapido", "mixto"}:
            kinetic_level = "dynamic"
        else:
            kinetic_level = "soft"
    if kinetic_level not in {"soft", "dynamic", "intense"}:
        kinetic_level = "dynamic"

    transition_preset = str(
        raw_style.get("transitionPreset")
        or timeline_payload.get("transitionPreset")
        or raw_meta.get("transitionPreset")
        or ""
    ).strip().lower()
    if not transition_preset:
        transitions = style_profile.get("transitions") if isinstance(style_profile.get("transitions"), list) else []
        normalized_transitions = {str(x).strip().lower() for x in transitions if str(x).strip()}
        transition_preset = "swipe" if normalized_transitions.intersection({"whip", "zoom_cut", "wipe"}) else "slide"
    if transition_preset not in {"slide", "swipe", "pulse"}:
        transition_preset = "slide"

    feature_card_mode = str(
        raw_style.get("featureCardMode")
        or timeline_payload.get("featureCardMode")
        or raw_meta.get("featureCardMode")
        or "window"
    ).strip().lower()
    if feature_card_mode not in {"window", "plain"}:
        feature_card_mode = "window"

    custom_style = {}
    for key in ("primaryColor", "accentColor", "fontFamily"):
        value = raw_theme_config.get(key)
        if value is None:
            value = raw_theme_config.get(key[0].lower() + key[1:])
        if value is None and key == "fontFamily":
            value = raw_theme_config.get("headingFont") or raw_theme_config.get("bodyFont")
        if value:
            custom_style[key] = str(value)

    style = {
        "theme": theme,
        "primaryColor": str(raw_style.get("primaryColor") or custom_style.get("primaryColor") or theme_defaults["primaryColor"]),
        "accentColor": str(raw_style.get("accentColor") or custom_style.get("accentColor") or theme_defaults["accentColor"]),
        "fontFamily": str(raw_style.get("fontFamily") or custom_style.get("fontFamily") or theme_defaults["fontFamily"]),
        "layoutVariant": layout_variant,
        "kineticLevel": kinetic_level,
        "transitionPreset": transition_preset,
        "featureCardMode": feature_card_mode,
    }

    raw_features = raw_script.get("features") if isinstance(raw_script.get("features"), list) else []
    if not raw_features and isinstance(timeline_payload.get("features"), list):
        raw_features = timeline_payload.get("features")
    if not raw_features:
        scenes = timeline_payload.get("scenes") if isinstance(timeline_payload.get("scenes"), list) else []
        raw_features = _build_universal_features_from_scenes(scenes)

    features: list[dict] = []
    for idx, item in enumerate(raw_features or []):
        if not isinstance(item, dict):
            continue

        image_candidate = str(item.get("imagePath") or item.get("image") or item.get("src") or "")
        image_path = _normalize_static_asset_path(image_candidate)
        if image_path and _is_non_image_asset_path(image_path):
            logger.warning(
                "UniversalCommercial skipped non-image feature asset: {}",
                image_candidate,
            )
            image_path = ""

        feature = {
            "title": str(item.get("title") or item.get("name") or f"Feature {idx + 1}").strip(),
            "subtitle": str(item.get("subtitle") or item.get("description") or "Beneficio principal").strip(),
        }
        if image_path:
            feature["imagePath"] = image_path
        features.append(feature)

    if not features:
        features = [
            {
                "title": "Narrativa visual",
                "subtitle": "Secuencia comercial clara y orientada a conversion",
            }
        ]

    hook = str(
        raw_script.get("hook")
        or timeline_payload.get("hook")
        or metadata.get("gancho")
        or metadata.get("titulo")
        or "Convierte atencion en accion"
    ).strip()
    solution = str(
        raw_script.get("solution")
        or timeline_payload.get("solution")
        or "Presenta tu producto con ritmo y claridad"
    ).strip()
    cta = str(
        raw_script.get("cta")
        or timeline_payload.get("cta")
        or timeline_payload.get("callToAction")
        or "Conoce mas"
    ).strip()

    raw_audio = timeline_payload.get("audio") if isinstance(timeline_payload.get("audio"), dict) else {}
    music = timeline_payload.get("music") if isinstance(timeline_payload.get("music"), dict) else {}
    bgm = _normalize_static_asset_path(str(raw_audio.get("bgmPath") or music.get("src") or ""))

    try:
        volume = float(raw_audio.get("volume") if raw_audio.get("volume") is not None else 0.4)
    except (TypeError, ValueError):
        volume = 0.4
    volume = max(0.0, min(1.0, volume))

    normalized: dict = {
        "projectInfo": {
            "name": project_name,
            "tagline": str(raw_project.get("tagline") or "").strip(),
            "website": str(raw_project.get("website") or "").strip(),
            "industry": str(raw_project.get("industry") or "").strip(),
        },
        "style": style,
        "script": {
            "hook": hook,
            "solution": solution,
            "features": features,
            "cta": cta,
        },
        "audio": {
            "volume": volume,
        },
        "theme": theme,
        "playbook": playbook,
        "layoutVariant": layout_variant,
        "kineticLevel": kinetic_level,
        "transitionPreset": transition_preset,
        "featureCardMode": feature_card_mode,
    }

    if bgm:
        normalized["audio"]["bgmPath"] = bgm

    if raw_theme_config:
        normalized["themeConfig"] = dict(raw_theme_config)

    return normalized


def _build_universal_features_from_scenes(scenes: list[dict]) -> list[dict]:
    """Approximate UniversalCommercial features from generic scene entries."""
    features: list[dict] = []
    for idx, scene in enumerate(scenes):
        if not isinstance(scene, dict):
            continue

        title = str(scene.get("title") or scene.get("text") or scene.get("id") or "").strip()
        subtitle = str(scene.get("subtitle") or scene.get("sceneText") or "").strip()
        scene_kind = str(scene.get("kind") or "").strip().lower()
        image_candidate = str(scene.get("imagePath") or "").strip()
        if not image_candidate and scene_kind in {"image", "photo", "still"}:
            image_candidate = str(scene.get("src") or "")
        if not image_candidate and not scene_kind:
            image_candidate = str(scene.get("src") or "")

        image_path = _normalize_static_asset_path(image_candidate)
        if image_path and _is_non_image_asset_path(image_path):
            image_path = ""

        if not title:
            title = f"Feature {idx + 1}"
        if not subtitle:
            subtitle = "Beneficio principal"

        entry = {
            "title": title,
            "subtitle": subtitle,
        }
        if image_path:
            entry["imagePath"] = image_path
        features.append(entry)

        if len(features) >= 4:
            break

    return features


def _to_file_uri(value: str) -> str:
    """Normalize asset paths for CinematicRenderer staticFile()/URL handling.

    - HTTP(S)/data/file URIs pass-through.
    - Local files under workspace become "workspace/..." static paths.
    - Other local paths stay absolute (best-effort fallback).
    """
    src = (value or "").strip()
    if not src:
        return src

    lowered = src.lower()
    if lowered.startswith("http://") or lowered.startswith("https://") or lowered.startswith("data:"):
        return src
    if lowered.startswith("file://"):
        return src

    try:
        path = Path(src).resolve()
        workspace_dir = settings.workspace.resolve()
        if path.is_relative_to(workspace_dir):
            rel = path.relative_to(workspace_dir)
            return f"workspace/{rel.as_posix()}"
        return str(path)
    except Exception:
        return src


def _canonical_asset_reference(value: str) -> str:
    """Normalize an asset reference to compare across URL/static/file forms."""
    raw = str(value or "").strip()
    if not raw:
        return ""

    raw = unquote(raw)
    lowered = raw.lower()
    if lowered.startswith("http://") or lowered.startswith("https://"):
        marker = "/public/"
        idx = lowered.find(marker)
        if idx >= 0:
            raw = raw[idx + len(marker):]
    elif lowered.startswith("file://"):
        raw = raw[7:]

    raw = raw.split("?", 1)[0].split("#", 1)[0]
    return raw.replace("\\", "/").lstrip("/")


def _extract_failed_image_sources(stderr_text: str) -> set[str]:
    """Extract image URLs Remotion failed to decode from stderr."""
    if not stderr_text:
        return set()

    sources: set[str] = set()
    matches = re.findall(r"Could not load image with source ([^,\s]+)", stderr_text, flags=re.IGNORECASE)
    for source in matches:
        normalized = _canonical_asset_reference(source)
        if normalized:
            sources.add(normalized)
    return sources


def _sanitize_non_image_sources_in_props(
    props: dict,
    composition_id: str,
    blocked_sources: Optional[set[str]] = None,
) -> int:
    """Remove/convert image-like props that actually point to video/audio assets."""
    blocked = {
        _canonical_asset_reference(item)
        for item in (blocked_sources or set())
        if str(item or "").strip()
    }

    def _must_strip(source_value: str) -> bool:
        normalized = _canonical_asset_reference(source_value)
        if not normalized:
            return False
        if blocked and normalized in blocked:
            return True
        return _is_non_image_asset_path(normalized)

    sanitized = 0

    if composition_id == "UniversalCommercial":
        script = props.get("script") if isinstance(props.get("script"), dict) else {}
        features = script.get("features") if isinstance(script.get("features"), list) else []
        for feature in features:
            if not isinstance(feature, dict):
                continue
            image_path = str(feature.get("imagePath") or "").strip()
            if image_path and _must_strip(image_path):
                feature.pop("imagePath", None)
                sanitized += 1
        return sanitized

    scenes = props.get("scenes") if isinstance(props.get("scenes"), list) else []
    for scene in scenes:
        if not isinstance(scene, dict):
            continue
        if str(scene.get("kind") or "").strip().lower() != "image":
            continue

        src = str(scene.get("src") or "").strip()
        if src and _must_strip(src):
            scene["kind"] = "video"
            scene.pop("animation", None)
            scene.pop("animationIntensity", None)
            scene.pop("animationDirection", None)
            scene.pop("overlayParticles", None)
            sanitized += 1

    return sanitized


def _materialize_workspace_assets(props: dict) -> None:
    """Copy workspace-referenced assets into remotion public/workspace.

    This avoids relying on symlink behavior in bundled render temp dirs.
    """
    public_workspace = REMOTION_DIR / "public" / "workspace"
    public_workspace.mkdir(parents=True, exist_ok=True)
    workspace_dir = settings.workspace.resolve()

    def _source_and_static(src: str) -> tuple[Optional[Path], str]:
        raw = (src or "").strip()
        if not raw:
            return None, raw

        lowered = raw.lower()
        if lowered.startswith("http://") or lowered.startswith("https://") or lowered.startswith("data:"):
            return None, raw

        if lowered.startswith("workspace/"):
            local = settings.workspace.parent / raw
            return local, raw.replace("\\", "/")

        if lowered.startswith("file://"):
            decoded = unquote(raw[7:])
            local = Path(decoded)
        else:
            local = Path(raw)

        try:
            local = local.resolve()
            if local.is_relative_to(workspace_dir):
                rel = local.relative_to(workspace_dir)
                return local, f"workspace/{rel.as_posix()}"
        except Exception:
            return None, raw

        return None, raw

    def _materialize(entry: dict, key: str = "src") -> None:
        if not isinstance(entry, dict):
            return
        src = str(entry.get(key, "") or "")
        local_path, static_src = _source_and_static(src)
        if local_path and local_path.exists() and local_path.is_file():
            rel = static_src.replace("workspace/", "", 1)
            dest = public_workspace / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            # When public/workspace is a symlink to workspace, source and dest can be identical.
            try:
                if dest.exists() and dest.resolve() == local_path.resolve():
                    entry[key] = static_src
                    return
            except Exception:
                pass

            try:
                shutil.copy2(local_path, dest)
            except shutil.SameFileError:
                # Safe no-op: file already available at target path.
                pass
            entry[key] = static_src

    for scene in props.get("scenes", []):
        if isinstance(scene, dict):
            _materialize(scene, "src")

    soundtrack = props.get("soundtrack")
    if isinstance(soundtrack, dict):
        _materialize(soundtrack, "src")

    music = props.get("music")
    if isinstance(music, dict):
        _materialize(music, "src")

    audio = props.get("audio")
    if isinstance(audio, dict):
        _materialize(audio, "bgmPath")

    script = props.get("script")
    if isinstance(script, dict) and isinstance(script.get("features"), list):
        for feature in script.get("features", []):
            if isinstance(feature, dict):
                _materialize(feature, "imagePath")


def _parse_ass_words(subtitles_path: Optional[Path]) -> list[dict]:
    """Parse ASS subtitles into word-level captions for Remotion overlay."""
    if not subtitles_path or not subtitles_path.exists():
        return []

    words: list[dict] = []
    try:
        lines = subtitles_path.read_text(encoding="utf-8", errors="ignore").splitlines()
        for line in lines:
            if not line.startswith("Dialogue:"):
                continue

            parts = line.split(",", 9)
            if len(parts) < 10:
                continue

            start_s = _ass_time_to_seconds(parts[1])
            end_s = _ass_time_to_seconds(parts[2])
            if end_s <= start_s:
                continue

            raw_text = parts[9]
            if not _append_karaoke_words(words, raw_text, start_s, end_s):
                _append_uniform_words(words, raw_text, start_s, end_s)
    except Exception as exc:
        logger.debug(f"ASS parsing failed for Remotion captions: {exc}")

    return words


def _append_karaoke_words(words: list[dict], raw_text: str, start_s: float, end_s: float) -> bool:
    """Extract precise timings from ASS karaoke tags (\\k/\\kf/\\ko)."""
    karaoke_re = re.compile(r"\{\\(?:k|K|kf|KF|ko|KO)(\d+)\}")
    matches = list(karaoke_re.finditer(raw_text or ""))
    if not matches:
        return False

    chunks: list[tuple[float, list[str]]] = []
    for idx, match in enumerate(matches):
        next_pos = matches[idx + 1].start() if idx + 1 < len(matches) else len(raw_text)
        chunk_text = raw_text[match.end() : next_pos]
        chunk_text = re.sub(r"\{[^}]*\}", "", chunk_text)
        chunk_text = chunk_text.replace("\\N", " ").replace("\\n", " ")
        chunk_text = re.sub(r"\s+", " ", chunk_text).strip()
        tokens = _tokenize_caption_words(chunk_text)
        if not tokens:
            continue

        dur_cs = max(1, int(match.group(1) or 0))
        chunks.append((dur_cs / 100.0, tokens))

    if not chunks:
        return False

    total_tag_span = sum(span for span, _ in chunks)
    line_span = max(0.04, end_s - start_s)
    scale = (line_span / total_tag_span) if total_tag_span > 0 else 1.0

    cursor = start_s
    line_words: list[dict] = []
    for chunk_span, tokens in chunks:
        alloc = max(0.04, chunk_span * scale)
        step = alloc / max(len(tokens), 1)
        for token in tokens:
            w_start = cursor
            w_end = min(end_s, cursor + step)
            line_words.append(
                {
                    "word": token,
                    "startMs": int(round(w_start * 1000)),
                    "endMs": int(round(w_end * 1000)),
                }
            )
            cursor = w_end

    if not line_words:
        return False

    last_end = int(round(end_s * 1000))
    if line_words[-1]["endMs"] < last_end:
        line_words[-1]["endMs"] = last_end

    for item in line_words:
        if item["endMs"] <= item["startMs"]:
            item["endMs"] = item["startMs"] + 40
        words.append(item)
    return True


def _append_uniform_words(words: list[dict], raw_text: str, start_s: float, end_s: float) -> None:
    """Fallback parser for ASS lines without karaoke tags."""
    text = re.sub(r"\{[^}]*\}", "", raw_text or "")
    text = text.replace("\\N", " ").replace("\\n", " ")
    text = re.sub(r"\s+", " ", text).strip()
    tokens = _tokenize_caption_words(text)
    if not tokens:
        return

    span = max(0.04, end_s - start_s)
    step = span / len(tokens)
    cursor = start_s
    for token in tokens:
        start_ms = int(round(cursor * 1000))
        end_ms = int(round(min(end_s, cursor + step) * 1000))
        if end_ms <= start_ms:
            end_ms = start_ms + 40
        words.append({"word": token, "startMs": start_ms, "endMs": end_ms})
        cursor += step


def _tokenize_caption_words(text: str) -> list[str]:
    return re.findall(r"[A-Za-z0-9ÁÉÍÓÚáéíóúÑñÜü]+|[^\s]", text or "")


def _ass_time_to_seconds(value: str) -> float:
    """Convert ASS timestamp (H:MM:SS.CS) to seconds."""
    try:
        hms, centis = value.strip().split(".")
        hh, mm, ss = hms.split(":")
        return int(hh) * 3600 + int(mm) * 60 + int(ss) + (int(centis) / 100.0)
    except Exception:
        return 0.0


def _remotion_output_quality_issue(video_path: Path) -> str:
    """Return a short reason when rendered output is clearly broken.

    This is intentionally lightweight and conservative so Remotion keeps being
    used when healthy, while obviously bad outputs trigger FFmpeg fallback.
    """
    try:
        probe = subprocess.run(
            [
                "ffprobe", "-v", "quiet",
                "-print_format", "json",
                "-show_format", "-show_streams",
                str(video_path),
            ],
            capture_output=True,
            text=True,
            timeout=15,
        )
        if probe.returncode != 0:
            return "ffprobe failed"

        data = json.loads(probe.stdout or "{}")
        streams = data.get("streams", []) if isinstance(data, dict) else []
        video_dur = None
        audio_dur = None
        has_audio_stream = False

        for stream in streams:
            if not isinstance(stream, dict):
                continue
            ctype = stream.get("codec_type")
            dur = stream.get("duration")
            if ctype == "audio":
                has_audio_stream = True
            if dur is None:
                continue
            try:
                dur_f = float(dur)
            except Exception:
                continue
            if ctype == "video" and video_dur is None:
                video_dur = dur_f
            elif ctype == "audio" and audio_dur is None:
                audio_dur = dur_f

        if not has_audio_stream:
            return "missing audio stream"

        if video_dur and audio_dur and abs(video_dur - audio_dur) > 0.8:
            return f"av_desync video={video_dur:.2f}s audio={audio_dur:.2f}s"

        total_duration = None
        try:
            total_duration = float((data.get("format") or {}).get("duration", 0) or 0)
        except Exception:
            total_duration = None

        if total_duration and total_duration >= 5:
            silence = subprocess.run(
                [
                    "ffmpeg", "-i", str(video_path),
                    "-af", "silencedetect=noise=-40dB:d=2",
                    "-f", "null", "-",
                ],
                capture_output=True,
                text=True,
                timeout=35,
            )
            stderr = silence.stderr or ""
            durations = re.findall(r"silence_duration: ([\d.]+)", stderr)
            total_silence = sum(float(d) for d in durations)
            if total_silence > total_duration * 0.3:
                return (
                    f"excessive_silence {total_silence:.1f}s/"
                    f"{total_duration:.1f}s"
                )

    except Exception as exc:
        logger.debug(f"Remotion output sanity check skipped: {exc}")

    return ""


def setup_remotion_project() -> bool:
    """Initialize the Remotion project if not already set up."""
    if REMOTION_DIR.exists() and (REMOTION_DIR / "node_modules").exists():
        logger.debug("Remotion project already initialized")
        return True

    try:
        logger.info("🔧 Setting up Remotion project...")
        REMOTION_DIR.mkdir(parents=True, exist_ok=True)
        result = subprocess.run(
            ["npx", "-y", "create-video@latest", str(REMOTION_DIR), "--template", "blank"],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode == 0:
            logger.info("✅ Remotion project initialized")
            return True

        logger.warning(f"Remotion setup failed: {result.stderr[:300]}")
        return False
    except Exception as exc:
        logger.error(f"Remotion setup error: {exc}")
        return False
